### ISSUE TITLE
Default name for new repositories automatically lowercased

### ISSUE THREAD

**Issue by davidwales** [gitoqlok/helpdesk#11]
When I try to set the default name for new repositories, it automatically lowercases the text.
This means that I can't use the variable names, as they contain uppercase characters!

![image](https://user-images.githubusercontent.com/55477181/102026038-d4b45c00-3def-11eb-8bb3-ca6fc70cb37e.png)

**Comment by shatzibitten** [comment]
check please

**Comment by davidwales** [comment]
It's working now!
