### ISSUE TITLE
Gitoqlik adds "isBlueprintItem": true as a property of "qMetaDef" for the app and for each sheet.

### ISSUE THREAD

**Issue by davidwales** [gitoqlok/helpdesk#12]
I committed an app, then restored that commit to test a round-trip of the Qlik data.
Looking at the diff, I noticed that for the app, and for each sheet in the app, "qMetaDef" was modified to include the property:

```
"isBlueprintItem": true
```

See the diff screenshots below:
![image](https://user-images.githubusercontent.com/55477181/102026829-48586800-3df4-11eb-8774-f40701fb98c6.png)

![image](https://user-images.githubusercontent.com/55477181/102026849-6e7e0800-3df4-11eb-91a8-b52e70e26725.png)

**Comment by shatzibitten** [comment]
removed  in 1.7.9 version
